name: SonarCloud Analysis
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and Analyze
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Necessario per SonarCloud

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'zulu'
          cache: maven

      - name: Verifica JAVA_HOME
        run: echo "JAVA_HOME=$JAVA_HOME"

      - name: Imposta manualmente JAVA_HOME
        run: echo "JAVA_HOME=${{ env.JAVA_HOME }}" >> $GITHUB_ENV

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Download JavaFX
        run: |
          wget https://download2.gluonhq.com/openjfx/21.0.5/openjfx-21.0.5_linux-x64_bin-sdk.zip
          unzip openjfx-21.0.5_linux-x64_bin-sdk.zip -d $HOME/javafx-sdk/
          echo "JAVAFX_SDK_PATH=$HOME/javafx-sdk/javafx-sdk-21.0.5/lib" >> $GITHUB_ENV

      - name: Build the project
        run: mvn clean install -DskipTests -Djavafx.sdk.path=$JAVAFX_SDK_PATH
        env:
          JAVA_HOME: ${{ env.JAVA_HOME }}

      - name: Run tests
        run: mvn test -Djavafx.sdk.path=$JAVAFX_SDK_PATH
        env:
          JAVA_HOME: ${{ env.JAVA_HOME }}

      - name: SonarCloud Analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          JAVA_HOME: ${{ env.JAVA_HOME }}
        run: mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=FederickDS_progettoISPW
